version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - /home/$USER/mysql/db:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: lists
      MYSQL_USER: admin
      MYSQL_PASSWORD: testpwd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8080:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpw
        MYSQL_ROOT_PASSWORD: rootpw