name: lists-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Publish
      run: go build -ldflags "-s -w" -o "publish/bin"

    - uses: actions/upload-artifact@v2
      with:
        name: api-binaries
        path: publish

    - uses: actions/upload-artifact@v2
      with:
        name: terraform-files
        path: deploy/terraform

  plan_terraform:
    environment: prod 
    needs: build
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: terraform-files
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.14.3
    - name: Terraform init
      run: |
        terraform init

    - name: Terraform select workspace
      run: | 
        terraform workspace select prod
    
    - name: Terraform plan
      run: |
        terraform plan

  apply_terraform:
    environment: prod 
    needs: plan_terraform
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Download a terraform files
      uses: actions/download-artifact@v2
      with:
        name: terraform-files
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.14.3
    - name: Terraform init
      run: |
        terraform init

    - name: Terraform select workspace
      run: | 
        terraform workspace select prod
    
    - name: Terraform apply
      run: |
        terraform apply --auto-approve=true

  deploy_app:
  environment: prod
  needs: build
  name: Deploy prod
  runs-on: ubuntu-latest
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  steps:
    - name: Download application binaries
      uses: actions/download-artifact@v2
      with:
        name: api-binaries

    - name: Deploy to eb
      uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'deploy ${{ secrets.ENVIRONMENT_NAME }}'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-3"